[firebase]
type = "service_account"
project_id = "expense-tracker-56c5c"
private_key_id = "3f0a4c6470581b40f56e356a73c78613e4913062"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMcBERSW+1mZqj
Ctqy2qcSpdzbK6k8mp4YitNYXXWfCY3K+0h3sxmoIcIQqwxZJkc41vh3OZymOQz2
sqcrRKgpwSF9IWC1AuwfDePbs0wFyMcn9ScExlpWZejOQ8ptEbWfY1gtKCnwdgBv
BS1VoraZPoNZPAVDWRWUrHjv/SX4Tl9ZbHwPO8DdrerRMP7MNSTUuK25fQwLK3GH
WaaJSDJnzaVsKu1PyACBgAj9F6NDenHlHvmpKUfIBCfzjI3cWxABK8n27AQ5qm+V
Sh+uGe7PqT315KV5RTzaXuURquFfVMYXVAmd7A33d4KC8u9JZsigop6pLGBAD0bB
BlZ3tPlnAgMBAAECggEAEKAnTmCxARoNTXSABZ4qvfIw+STE8UtHtfCjfS+yKMb2
Br7GjW/j+cLipxVdMZ2fZ1vZvmRrVpWtwratSdaePTFzuXSuvZNckK5bmSd5jfNE
+WOb+Tm76TcF2eRnpwgS9tpCHP+dRyA2XjdgqoxLGkC1t0ErOM3OJ5ZnijWfOJRB
DNo4uZXrXcDiy6YARKTzTrGmoyWR62bXoRcdgZVYBLmTHX79zJ0cfNUW+BNwR25K
Mbwe1wtkyCvzoclfS52G3ph5K1M2OVw4u+Y7zEe8LQTIV3tFnHfmOpD4QxxkZs7B
DHhW+fVW7MCkR+7rQfkwF2G5gxB4PdCWz+UOvjOXxQKBgQDpspM8+NApKhbn8sfe
EyvrTbNb2VqOZi2h9lso49xNiYZKX6/d9uWx2UBSJ4i3BLm4Lt+8l7KHfPzGdt5K
91S6fUidKJd3pqSIyMeRQXA5rQyCOf5SChnu5Yq8VdAZRk5SA9S+90t8ZXUF4oA6
MUQPVCq1bnqfU4IbohndbVT9WwKBgQDf8qaBeSd6zTGRjGAwKcNdCmqSQP9GWvrK
+Q9GCycBYcrrj7hegAVD8Z61XHtaBn+XhCcqbuZ6kgizl6LvoWhzgrLthxp8HCsv
UVJv8nErnDHVZ4ZXrHGpuXrGDmpbC1VNHZvSIJTfnAfsKiwb/YczSy4r6Kj/OSSY
WRVMfze15QKBgGR3HpEhretkasCAQKgZudHIb4jW4fVBu/BaxknH21eB/bdPd32G
vKw+Z0ZqNH3pjCXAEPM0i81vUAPJ6jp0JXqejW7ymlsXyrf7CMBLT4GcATqiz9BZ
A1kOWRwqD/ItpVHgz77g9RSfUTWcb9+UelvUpR+mRRTlg5N5loD4lYbtAoGBAJqi
jZCXXMhxyYlr+bsoC0tCdwYYNWyaQ9RFl+NQrhVJNnnjmnY+ReR9gY5Plqk6FX5E
9Vpai3EVR0bjLNH0jRA9rllPUd1jAfrBV4APU0++obZurpf5bd65QWpi59OIBtWh
3UeB0ep5bgsHr7+AF4w2nGIbXB4nkfpUgN16drh1AoGAV6IbR3TnGRxHwE8x8MT2
UlqBpaDzG6jm6PA370arJi60TAW1jegbuvEhmlDf95lkiU4LsujM9WYbUWqRBqgp
nDs2vkEPbSB3h42eewpvbgPxt5MEYzc5JHuFplRQzeZDPOkslvvD+zZ+EmH3zUg+
LngDysaYWWIRGDoJiXGBHKw=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-uaae1@expense-tracker-56c5c.iam.gserviceaccount.com"
client_id = "111418949272096718666"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-uaae1%40expense-tracker-56c5c.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
